### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by charbasket** [achimmihca/EclipseLineShortcuts#1]
Hi, 

I installed it via the Eclipse Marketplace and it says is installed, but i can´t get it to work. Any ideas what could i have done wrong?

Thanks.

**Comment by achimmihca** [comment]
It seems I forgot to add a note about the JDK version on the Marketplace.

Make sure that you run your Eclipse instance on JDK 11. Using JDK 8 will not work without any error message.
You can configure the Java VM that is used by Eclipse using the -vm option in eclipse.ini, which is explained [here](https://wiki.eclipse.org/Eclipse.ini#Specifying_the_JVM).

If you use JDK 11 already, make sure that the shortcuts are set correctly (see screenshot on Eclipse Marketplace).

**Comment by charbasket** [comment]
Okay, thanks, now it works

**Comment by charbasket** [comment]
Sorry to ask again, but now it appears like this, but still doesnt work for me, any ideas what i could be doing wrong?
![WhatsApp Image 2020-02-10 at 22 41 58](https://user-images.githubusercontent.com/60796205/74192830-9772c100-4c56-11ea-904b-6c493bc3acb6.jpeg)

**Comment by achimmihca** [comment]
Mmmmh, it should work now.

Are there any other commands that use the same shortcut? I should be the only command with this shortcut.

You can try if the action itself is doing anything by typing the command into the "Quick access" search of Eclipse. If this does not work, then triggering it via shortcut will also not work.

I wonder if you are using a special editor maybe? Please try a plain txt file and see if it is working there.

**Comment by achimmihca** [comment]
![recenteditors-trigger-action-quick-access](https://user-images.githubusercontent.com/14967033/74465975-a47df300-4e96-11ea-8b70-7e8be737ae67.png)

**Comment by achimmihca** [comment]
Is it working for you now? If so, then please close this issue.

**Comment by charbasket** [comment]
Sorry i didnt respond, its working on pc but not on Mac.
